// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDA1YXKz_K1ssro93FwTfd8FNpVkuSJO04',
    appId: '1:847381653180:web:20cbbbea3f1dcf970b52b9',
    messagingSenderId: '847381653180',
    projectId: 'fitpalv3',
    authDomain: 'fitpalv3.firebaseapp.com',
    storageBucket: 'fitpalv3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCADqqQq4k36RJkRrk2zPYLZPNrKZxV1xc',
    appId: '1:847381653180:android:24d472fb5c23d7e00b52b9',
    messagingSenderId: '847381653180',
    projectId: 'fitpalv3',
    storageBucket: 'fitpalv3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7DezHJ8uyV1flxSCX5YeY4ck8Q6edD0o',
    appId: '1:847381653180:ios:83a63873bdc1359e0b52b9',
    messagingSenderId: '847381653180',
    projectId: 'fitpalv3',
    storageBucket: 'fitpalv3.appspot.com',
    iosBundleId: 'com.group22.fitpal.fitpal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7DezHJ8uyV1flxSCX5YeY4ck8Q6edD0o',
    appId: '1:847381653180:ios:72f4efe5383d83ad0b52b9',
    messagingSenderId: '847381653180',
    projectId: 'fitpalv3',
    storageBucket: 'fitpalv3.appspot.com',
    iosBundleId: 'com.group22.fitpal.fitpal.RunnerTests',
  );
}
